---
- name: Deploy Laravel Application
  host: 192.168.33.11
  become: yes
  tasks:
    - name: Copy the deployment script to the Slave node
      copy:
        src: AltschoolSSE.sh
        dest: /tmp/AltschoolSSE.sh
        mode: '0755'
      delegate_to: localhost  # This copies the script from the master VM to the slave VM

    - name: Execute the deployment script on the Slave node
      command: /tmp/AltschoolSSE.sh
      args:
        chdir: /tmp
      delegate_to: localhost  # Runs the script on the slave VM

    - name: Verify that Laravel is accessible
      wait_for:
        host: 192.168.33.11  
        port: 80  
        state: started
        timeout: 60
      ignore_errors: yes

- name: Create slavephp Cron Job
  hosts: 192.168.33.11
  become: yes
  tasks:
    - name: Add the slavephp cron job
      cron:
        name: "uptime_check"
        minute: 0
        hour: 0
        job: "uptime > /var/log/uptime.log 2>&1"
